const ACTIONS = {
  CLICK_BOOK: 'CLICK_BOOK',
  SEARCH_BOOKS: 'SEARCH_BOOKS',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SHOW_FOUND: 'SHOW_FOUND',
  HIDE_FOUND: 'HIDE_FOUND',
  SET_NOTHING_FOUND: 'SET_NOTHING_FOUND',
  START_PRELOADER: 'START_PRELOADER',
  STOP_PRELOADER: 'STOP_PRELOADER',
};

export default ACTIONS;
